using seeds.Dal.Model;

public class Program
{
    public static void Main()
    {
        char familyChar = ':';

        /// Read the content of the file
        string mdFileIn = "../../../../topics.md";
        string csFileOut = "../../../../seeds.Api/Data/AutoGeneratedDataSeeder.cs";
        List<string> lines = File.ReadAllLines(mdFileIn).ToList();
        StreamWriter writer = new(csFileOut, false);

        /// Define variables to store topics and category
        List<Topic> Topics = new();
        List<Family> Fams = new();
        string catKey = null!;
        string catName = null!;
        string famName = null!;
        int probablePreference = 0;

        writer.WriteLine("using seeds.Dal.Model;");
        writer.WriteLine("");
        writer.WriteLine("namespace seeds.Api.Data;");
        writer.WriteLine("");
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// In VS22, press Ctrl+K Ctrl+D to indent the code nicely.");
        writer.WriteLine("/// (In VS22, pressing Ctrl+M Ctrl+L collapses everything.)");
        writer.WriteLine("/// Copy the function into the actual DataSeeder.cs");
        writer.WriteLine("/// Please check the file for errors, parsing might have not worked perfectly.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public class AutoGeneratedFromTopicsMdFile");
        writer.WriteLine("{");
        writer.WriteLine($"List<Category> Cats = new();");
        writer.WriteLine($"List<Family> Fams = new();");
        writer.WriteLine($"List<Topic> Topics = new();");
        writer.WriteLine("");
        writer.WriteLine("public void PopulateCatsFamsTopics() {");
        writer.WriteLine($"List<string> famTopicsString;");
        writer.WriteLine($"List<Topic> famTopics;");
        foreach (string line in lines)
        {
            if (line.StartsWith("## `"))
            {
                if (catKey != null) { writer.WriteLine("#endregion"); }
                /// Extract category key and name
                catKey = line.Split('`')[1].Split(' ')[0].Trim();
                catName = line.Split('`')[1].Split('-')[1].Trim();
                writer.WriteLine("");
                writer.WriteLine($"#region {catKey} - {catName}");
                writer.WriteLine($"Cats.Add(new(){{ Key = \"{catKey}\", Name = \"{catName}\" }});");
            }
            else if (line.Split('`').Count() > 1 && line.Split('`')[0].Length < 9 && line.Split('`')[0].Contains('.') && line.Contains('{') && line.Contains('}') && line.Contains(familyChar))
            {
                writer.WriteLine("");
                /// Extract family name
                famName = line.Split('`')[1].Split(familyChar)[0].Trim();
                /// Extract family members
                List<string> famTopicsNames = line.Split('`')[1].Split('{')[1].Split('}')[0].Split(',').ToList();
                /// populate C# List<string>
                string wLine = "famTopicsString = new() { ";
                foreach (string topicName in famTopicsNames) { wLine += $" \"{topicName.Trim()}\","; }
                wLine += " };";
                writer.WriteLine(wLine);
                /// populate C# List<Topic>
                List<Topic> famTopics = famTopicsNames.Select(name => new Topic()
                { CategoryKey = catKey, Name = $"{famName}{familyChar} {name.Trim()}" }).ToList();
                writer.WriteLine("famTopics = famTopicsString.Select(name => new Topic()");
                writer.WriteLine($"{{CategoryKey = \"{catKey}\", Name = $\"{famName}{familyChar} {{name.Trim()}}\"}}).ToList();");
                /// add C# Family
                //Fams.Add(new() { CategoryKey = catKey, Name = line.Split('`')[1].Split(familyChar)[0].Trim(), Topics = famTopics });
                writer.WriteLine($"Fams.Add(new(){{ CategoryKey = \"{catKey}\", Name = \"{line.Split('`')[1].Split(familyChar)[0].Trim()}\", Topics = famTopics }});");
                /// add C# Topic of Family
                //foreach (var topic in famTopics) { Topics.Add(topic); }
                writer.WriteLine("foreach(var topic in famTopics) { Topics.Add(topic); }");
            }
            else if (line.Split('`').Count() > 1 && line.Split('`')[0].Length < 9 && line.Split('`')[0].Contains('.'))
            {
                /// populate C# Topic
                //Topics.Add(new Topic { CategoryKey = catKey, Name = line.Split('`')[1] });
                writer.WriteLine($"Topics.Add(new() {{ CategoryKey = \"{catKey}\", Name = \"{line.Split('`')[1]}\" }});");
            }
            else if (line.Contains("- preference: "))
            {
                /// Extract probable preference of the family
                probablePreference = Convert.ToInt16(line.Split(' ', StringSplitOptions.RemoveEmptyEntries)[^1]);
                //Fams[^1].ProbablePreference = probablePreference;
                /// add line of probablePreference to after all of the families tags
                writer.WriteLine($"Fams[^1].ProbablePreference = {probablePreference};");
                writer.WriteLine("");
            }
        }
        writer.WriteLine("#endregion");
        writer.WriteLine("}");
        writer.WriteLine(""); 
        writer.WriteLine("}");
        writer.Close();
        writer.Dispose();
    }
}
