using seeds.Dal.Model;

public class Program
{
    public static void Main()
    {
        char familyChar = ':';

        /// Read the content of the file
        string mdTopicsIn = "../../../../topics.md";
        string mdIdeasIn = "../../../../idea-seeds.md";
        string csOut = "../../../../seeds.Api/Data/AutoGeneratedDataSeeder.cs";
        List<string> topicsLines = File.ReadAllLines(mdTopicsIn).ToList();
        List<string> ideasLines = File.ReadAllLines(mdIdeasIn).ToList();
        StreamWriter writer = new(csOut, false);

        // Define variables to store data here
        List<Category> Cats = new();
        List<Topic> Topics = new();
        List<Family> Fams = new();
        List<User> Users = new();
        List<Idea> Ideas = new();

        writer.WriteLine("using System.Globalization;");
        writer.WriteLine("using seeds.Dal.Model;");
        writer.WriteLine("");
        writer.WriteLine("namespace seeds.Api.Data;");
        writer.WriteLine("");
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// In VS22, press Ctrl+K Ctrl+D to indent the code nicely.");
        writer.WriteLine("/// (In VS22, pressing Ctrl+M Ctrl+L collapses everything.)");
        writer.WriteLine("/// Copy the function into the actual DataSeeder.cs");
        writer.WriteLine("/// Please check the file for errors, parsing might have not worked perfectly.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public class AutoGeneratedFromMdFiles");
        writer.WriteLine("{");
        writer.WriteLine($"List<{nameof(Category)}> Cats = new();");
        writer.WriteLine($"List<{nameof(Family)}> Fams = new();");
        writer.WriteLine($"List<{nameof(Topic)}> Topics = new();");
        writer.WriteLine($"List<{nameof(Idea)}> Ideas = new();");
        writer.WriteLine($"List<{nameof(User)}> Users = new();");
        writer.WriteLine("");

        #region topics.md
        string catKey = null!;
        string catName = null!;
        string famName = null!;
        int probablePreference = 0;
        List<string> famTopicsString = new();
        List<Topic> famTopics = new();

        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// This function is copied from seeds.Api.AutoGeneratedDataSeeder.cs,");
        writer.WriteLine("/// which in turn is generated from ../topics.md by MdConverter.Program.cs");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public void PopulateCatsFamsTopics() {");
        writer.WriteLine($"List<string> famTopicsString;");
        writer.WriteLine($"List<{nameof(Topic)}> famTopics;");
        foreach (string line in topicsLines)
        {
            if (line.StartsWith("## `"))
            {
                if (catKey != null) { writer.WriteLine("#endregion"); }
                // Extract category key and name
                catKey = line.Split('`')[1].Split(' ')[0].Trim();
                catName = line.Split('`')[1].Split('-')[1].Trim();
                Cats.Add(new() { Key = catKey, Name = catName });
                writer.WriteLine("");
                writer.WriteLine($"#region {catKey} - {catName}");
                writer.WriteLine($"Cats.Add(new(){{ {nameof(Category.Key)} = \"{catKey}\", " +
                    $"{nameof(Category.Name)} = \"{catName}\" }});");
            }
            else if (line.Split('`').Count() > 1 && line.Split('`')[0].Length < 9 && line.Split('`')[0].Contains('.') && line.Contains('{') && line.Contains('}') && line.Contains(familyChar))
            {
                writer.WriteLine("");
                // Extract family name
                famName = line.Split('`')[1].Split(familyChar)[0].Trim();
                // Extract family members
                famTopicsString = line.Split('`')[1].Split('{')[1].Split('}')[0].Split(',').ToList();
                // populate C# List<string>
                string wLine = "famTopicsString = new() { ";
                foreach (string s in famTopicsString) { wLine += $" \"{s.Trim()}\","; }
                wLine += " };";
                writer.WriteLine(wLine);
                // populate C# List<Topic>
                famTopics = famTopicsString.Select(name => new Topic()
                { CategoryKey = catKey, Name = $"{famName}{familyChar} {name.Trim()}" }).ToList();
                writer.WriteLine($"famTopics = famTopicsString.Select(name => new {nameof(Topic)}()");
                writer.WriteLine($"{{{nameof(Topic.CategoryKey)} = \"{catKey}\", " +
                    $"{nameof(Topic.Name)} = $\"{famName}{familyChar} {{name.Trim()}}\"}}).ToList();");
                // add C# Family
                Fams.Add(new() { CategoryKey = catKey, Name = line.Split('`')[1].Split(familyChar)[0].Trim(), Topics = famTopics });
                writer.WriteLine($"Fams.Add(new(){{ {nameof(Family.CategoryKey)} = \"{catKey}\", " +
                    $"{nameof(Family.Name)} = \"{line.Split('`')[1].Split(familyChar)[0].Trim()}\", " +
                    $"{nameof(Family.Topics)} = famTopics }});");
                // add C# Topic of Family
                foreach (var topic in famTopics) { Topics.Add(topic); }
                writer.WriteLine($"foreach(var topic in famTopics) {{{nameof(Topics)}.Add(topic); }}");
            }
            else if (line.Split('`').Count() > 1 && line.Split('`')[0].Length < 9 && line.Split('`')[0].Contains('.'))
            {
                // populate C# Topic
                Topics.Add(new Topic { CategoryKey = catKey, Name = line.Split('`')[1] });
                writer.WriteLine($"{nameof(Topics)}.Add(new() {{ {nameof(Topic.CategoryKey)} = " +
                    $"\"{catKey}\", {nameof(Topic.Name)} = \"{line.Split('`')[1]}\" }});");
            }
            else if (line.Contains("- preference: "))
            {
                // Extract probable preference of the family
                probablePreference = Convert.ToInt16(line.Split(' ', StringSplitOptions.RemoveEmptyEntries)[^1]);
                Fams[^1].ProbablePreference = probablePreference;
                // add line of probablePreference to after all of the families tags
                writer.WriteLine($"Fams[^1].{nameof(Family.ProbablePreference)} = {probablePreference};");
                writer.WriteLine("");
            }
        }
        writer.WriteLine("#endregion");
        writer.WriteLine("}");
        writer.WriteLine("");
        #endregion

        #region idea-seeds.md
        string creatorName = null!;
        string ideaSection = null!;
        string description = null!;
        string timeString = null!;
        string ideaStringOfTopics = null!;
        string topicName = null!;
        bool newRegion = false;
        bool firstRegion = true;

        List<string> ideaTopicsString = new();
        List<Topic> ideaTopics = new();
        List<string> ideaSlidesString = new();
        Dictionary<int, string> slideNamesDict = new() {
            { 1, nameof(Idea.Slide1) },
            { 2, nameof(Idea.Slide2) },
            { 3, nameof(Idea.Slide3) },
        };
        Idea vanillaIdea = new();

        writer.WriteLine("");
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// This function is copied from seeds.Api.AutoGeneratedDataSeeder.cs,");
        writer.WriteLine("/// which in turn is generated from ../idea-seeds.md by MdConverter.Program.cs");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("public void PopulateIdeasAndTheirCreators() {");
        writer.WriteLine($"List<{nameof(Topic)}> ideaTopics = new();");
        for (int i = 0; i < ideasLines.Count; i++)
        {
            if (ideasLines[i].StartsWith("# "))
            {
                newRegion = true;
                // Extract idea section
                ideaSection = ideasLines[i].Split('#')[1].Trim();
            }
            else if (ideasLines[i].ToLower().Trim().StartsWith("- creatorname: "))
            {
                // extract CreatorName
                creatorName = string.Join(":", ideasLines[i].Trim().Split(':').Skip(1)).Trim();

                if (Users.FirstOrDefault(u => u.Username == creatorName) == null)
                {
                    // this username does not yet exist
                    Users.Add(new() { Username = creatorName });
                    writer.WriteLine($"Users.Add(new() {{ " +
                        $"{nameof(User.Username)} = \"{creatorName}\" }});");
                }
                Ideas[^1].CreatorName = creatorName;
            }
            else if (ideasLines[i].ToLower().Trim().StartsWith("- title: "))
            {
                // extract title
                Ideas[^1].Title = string.Join(":", ideasLines[i].Trim().Split(':').Skip(1)).Trim();
            }
            else if (ideasLines[i].ToLower().Trim().StartsWith("- slogan: "))
            {
                // extract slogan
                Ideas[^1].Slogan = string.Join(":", ideasLines[i].Trim().Split(':').Skip(1)).Trim();
            }
            else if (ideasLines[i].Trim().StartsWith("- {"))
            {
                // extract description
                description = "";
                ideasLines[i] = ideasLines[i].Trim().Substring(3);
                // we're in a possibly multi-line description
                while (!ideasLines[i].Trim().EndsWith("}"))
                {
                    description += ideasLines[i] + "\\n";
                    i++;
                }
                description += ideasLines[i].Trim().TrimEnd('}');

                Ideas[^1].Presentation = new() { Description = description };
            }
            else if (ideasLines[i].Trim().ToLower().StartsWith("- creationtime: "))
            {
                // extract DateTime as string like "2021-12-01"
                timeString = ideasLines[i].Split(":")[1].Trim();
            }
            else if (ideasLines[i].Trim().ToLower().StartsWith("- slide: "))
            {
                // add pic's URL to internal list
                ideaSlidesString.Add(string.Join(":", ideasLines[i].Split(":").Skip(1)).Trim());
            }
            else if (ideasLines[i].Trim().ToLower().StartsWith("- topics: "))
            {
                // extract list of topics:
                // first, cutoff "- topics: "
                ideaStringOfTopics = string.Join(":", ideasLines[i].Trim().Split(':').Skip(1)).Trim();

                // next, split list
                ideaTopicsString = ideaStringOfTopics.Split(';').ToList();

                // next, convert to actual topics
                // here, exceptions are thrown if the tags don't exist
                foreach (var s in ideaTopicsString)
                {
                    if (Topics.Where(t => t.Name == s.Trim()).Count() == 1)
                    {
                        catKey = Topics.First(t => t.Name == s.Trim()).CategoryKey;
                        topicName = Topics.First(t => t.CategoryKey == catKey &&
                                t.Name == s.Trim()).Name;
                    }
                    else if (s.Contains(':'))
                    {
                        catKey = Cats.First(c => c.Key == s.Split(':')[0].Trim()).Key;
                        topicName = Topics.First(t => t.CategoryKey == catKey &&
                                t.Name == s.Split(":")[1].Trim()).Name;
                    }
                    else
                    {
                        throw new Exception($"There exist " +
                                $"{Topics.Where(t => t.Name == s.Trim()).Count()}" +
                                $"tags with the name '{s.Trim()}'. " +
                                "The format is like \"CAT: family: topicname\".");
                    }
                    ideaTopics.Add(new()
                    {
                        CategoryKey = catKey,
                        Name = topicName
                    });
                }
            }
            if (ideasLines[i].StartsWith("## ") || i == ideasLines.Count - 1)
            {
                // Add last idea
                if (Ideas.Count > 0)
                {
                    if (Ideas[^1].Title == vanillaIdea.Title)
                    { throw new Exception("Title is Vanilla, please provide a \"- Title: \""); }
                    if (Ideas[^1].Slogan == vanillaIdea.Slogan)
                    { throw new Exception("Slogan is Vanilla, please provide a \"- Slogan: \""); }
                    writer.WriteLine($"Ideas.Add(new(){{");
                    writer.WriteLine($"{nameof(Idea.CreatorName)} = \"{Ideas[^1].CreatorName}\",");
                    writer.WriteLine($"{nameof(Idea.Title)} = \"{Ideas[^1].Title}\",");
                    writer.WriteLine($"{nameof(Idea.Slogan)} = \"{Ideas[^1].Slogan}\",");
                    if (description != "")
                    {
                        writer.WriteLine($"{nameof(Idea.Presentation)} = new() {{ " +
                            $"{nameof(Presentation.Description)} = " +
                            $"\"{Ideas[^1].Presentation.Description.Replace("\"", "\\\"")}\" }},");
                    }
                    if (timeString != "")
                    {
                        writer.WriteLine($"{nameof(Idea.CreationTime)} = " +
                            $"DateTime.ParseExact(\"{timeString}\",\"yyyy-MM-dd\", CultureInfo.InvariantCulture),");
                    }
                    if (ideaTopics.Count > 0)
                    {
                        writer.WriteLine($"{nameof(Idea.Topics)} = new() {{");
                        foreach (var topic in ideaTopics)
                        {
                            writer.WriteLine($"\t\t\t\tTopics.First(t => " +
                                $"t.{nameof(Topic.CategoryKey)} == \"{topic.CategoryKey}\" " +
                                $"&& t.{nameof(Topic.Name)} == \"{topic.Name}\"),");
                        }
                        writer.Write("\t\t\t},");
                    }
                    if (ideaSlidesString.Count > 0)
                    {
                        for (int j = 1; j <= ideaSlidesString.Count; j++)
                        {
                            writer.WriteLine($"{slideNamesDict[j]} = \"{ideaSlidesString[j - 1]}\",");
                        }
                    }
                    writer.WriteLine("});");
                }
                // Add placeholder for new ideas
                Ideas.Add(new());
                timeString = "";
                ideaTopics = new();
                ideaSlidesString = new();

                // print the regions
                if (newRegion)
                {
                    if (!firstRegion) { writer.WriteLine("#endregion"); }
                    writer.WriteLine("");
                    writer.WriteLine($"#region {ideaSection}");
                    newRegion = false;
                    firstRegion = false;
                }
            }
        }
        writer.WriteLine("#endregion");
        writer.WriteLine("}");
        writer.WriteLine("");
        #endregion

        writer.WriteLine("}");
        writer.Close();
        writer.Dispose();
    }
}
